In [9]:
import numpy as np

In [10]:
#Question1
x=np.array([4,6,7,1])
n=5
np.vander(x,n)

array([[ 256,   64,   16,    4,    1],
       [1296,  216,   36,    6,    1],
       [2401,  343,   49,    7,    1],
       [   1,    1,    1,    1,    1]])

In [11]:
np.vander(x,n,increasing=True)

array([[   1,    4,   16,   64,  256],
       [   1,    6,   36,  216, 1296],
       [   1,    7,   49,  343, 2401],
       [   1,    1,    1,    1,    1]])

In [12]:
np.vander(x,n,increasing=False)

array([[ 256,   64,   16,    4,    1],
       [1296,  216,   36,    6,    1],
       [2401,  343,   49,    7,    1],
       [   1,    1,    1,    1,    1]])

In [13]:
#Question2
def sarthak(a,n=3):
    cusum=np.cumsum(a,dtype=float)
    cusum[n:]=cusum[n:]-cusum[:-n]
    return cusum[n-1:]/n
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(sarthak(a, n=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
